### PR TITLE
Feature/add projects page

### PR DESCRIPTION
**Pull request by flo-bou**
Ticket : https://github.com/Project-OSmOSE/osmose-app/issues/115

### CODE REVIEW

**Comment by Qouagga** [comment]
It's a good job. You just forget to use black.

**Comment by flo-bou** [comment]
I did not write any python code. Do I really have to run black ?

**Comment by ixio** [comment]
Well not really, I just left master in a bad state sorry. We should fix this in the first PR to be merged, possibly one of yours ?

**Comment by flo-bou** [comment]
I don't know which one should be the first :/

**Review by ixio — APPROVED** [review]
LGTM

**Review by Qouagga — APPROVED** [review]

**Pull request merged**
